# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'firebaseApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firebaseApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

end

target 'firebaseApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firebaseApp-tvOS

  target 'firebaseApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
